version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    version_requirement_updates: "auto"
    # https://dependabot.com/docs/config-file/#automerged_updates
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
      - match:
          dependency_type: "all"
          update_type: "in_range"
      - match:
          dependency_name: "lodash"
      - match:
          dependency_name: "@types/*"
      - match:
          dependency_name: "@habx/*"
      - match:
          dependency_name: "lint-staged"
      - match:
          dependency_name: "typescript"
      - match:
          dependency_name: "@sentry/*"
          update_type: "semver:minor"
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
